def sanitize_node(node: str) -> str:
    """
    transforms a key from devdb into a valid python identifier
    """
    result = node.replace(".", "_")
    if not result.isidentifier():
        raise ValueError(f"unable to convert {node!r} to a valid python identifier")
    return result


def is_direct_subnode(parent: str, child: str) -> bool:
    if not parent:
        return "." not in child

    if not child.startswith(f"{parent}."):
        return False
    if "." in child.removeprefix(f"{parent}."):
        return False
    return True


def generate_stubs(devdb: dict[str, str]) -> str:
    code = ""
    code += "# Generated by annet/annlib/netdev/devdb/generate_stubs.py\n"
    code += "# DO NOT MODIFY!\n"
    code += "from __future__ import annotations\n"
    code += "\n"
    code += "from annet.annlib.netdev.views.hardware import HardwareLeaf\n"
    code += "\n"
    code += "\n"

    for node in sorted(devdb.keys()):
        code += f"class {sanitize_node(node)}(HardwareLeaf):\n"
        children = sorted(child for child in devdb.keys() if is_direct_subnode(node, child))
        for child in children:
            code += f"    {sanitize_node(child.removeprefix(f'{node}.'))}: {sanitize_node(child)}\n"
        if not children:
            code += "    ...\n"
        code += "\n"

    code += "class FakeHardwareView(HardwareLeaf):\n"
    code += '    """\n'
    code += "    NOT TO BE USED AT RUNTIME\n"
    code += "    fake base class for HardwareView that has annotations for entire devdb\n"
    code += '    """\n'
    code += "\n"
    children = sorted(child for child in devdb.keys() if is_direct_subnode("", child))
    for child in children:
        code += f"    {sanitize_node(child)}: {sanitize_node(child)}\n"
    if not children:
        # devdb is empty?
        code += "    ...\n"

    return code


def _main() -> None:
    import json
    import sys

    if len(sys.argv) != 3:
        print(f"Usage: {sys.executable} {sys.argv[0]} <devdb.json> <generated.pyi>")
        sys.exit(2)

    file_devdb = sys.argv[1]
    file_code = sys.argv[2]

    with open(file_devdb, "r") as f:
        devdb = json.load(f)

    with open(file_code, "w") as f:
        f.write(generate_stubs(devdb))


if __name__ == "__main__":
    _main()
