import itertools
import keyword
from collections.abc import Iterable, Iterator, Mapping


Node = tuple[str, ...]
ClassSignature = tuple[Node, tuple[tuple[str, Node], ...]]


def parse_devdb_key(key: str) -> tuple[tuple[str, ...], frozenset[int]]:
    parts = key.split(".")
    canonical: list[str] = []
    optional: set[int] = set()

    for index, part in enumerate(parts):
        if "?" in part:
            if part.count("?") != 1 or not part.endswith("?"):
                raise ValueError(f"invalid optional segment in devdb key {key!r}")
            if index == len(parts) - 1:
                raise ValueError(f"the final segment cannot be optional in devdb key {key!r}")
            part = part.removesuffix("?")
            optional.add(index)

        if not part.isidentifier() or keyword.iskeyword(part):
            raise ValueError(f"invalid segment {part!r} in devdb key {key!r}")
        canonical.append(part)

    return tuple(canonical), frozenset(optional)


def canonicalize_devdb_key(key: str) -> tuple[str, ...]:
    canonical, _ = parse_devdb_key(key)
    return canonical


def _optional_omissions(optional: frozenset[int]) -> Iterator[frozenset[int]]:
    for omitted_count in range(len(optional) + 1):
        for omitted in itertools.combinations(sorted(optional), omitted_count):
            yield frozenset(omitted)


def expand_devdb_key(key: str) -> set[str]:
    canonical, optional = parse_devdb_key(key)
    return {
        ".".join(part for index, part in enumerate(canonical) if index not in omitted)
        for omitted in _optional_omissions(optional)
    }


def sanitize_node(node: str) -> str:
    """
    transforms a key from devdb into a valid python identifier
    """
    result = node.replace(".", "_")
    if not result.isidentifier():
        raise ValueError(f"unable to convert {node!r} to a valid python identifier")
    return result


def _expanded_nodes(keys: Iterable[str]) -> dict[Node, Node]:
    canonical_owners: dict[Node, str] = {}
    owners: dict[Node, str] = {}
    targets: dict[Node, Node] = {}

    for key in keys:
        canonical, optional = parse_devdb_key(key)
        if canonical in canonical_owners and canonical_owners[canonical] != key:
            path = ".".join(canonical)
            raise ValueError(f"devdb keys {canonical_owners[canonical]!r} and {key!r} both generate path {path!r}")
        canonical_owners[canonical] = key

        for omitted in _optional_omissions(optional):
            expanded = []
            for index, part in enumerate(canonical):
                if index in omitted:
                    continue

                expanded.append(part)
                node = tuple(expanded)
                target = canonical[: index + 1]
                if node in targets and targets[node] != target:
                    path = ".".join(node)
                    raise ValueError(f"devdb keys {owners[node]!r} and {key!r} both generate path {path!r}")
                owners.setdefault(node, key)
                targets[node] = target

    return targets


def _children_by_node(nodes: Iterable[Node]) -> dict[Node, dict[str, Node]]:
    children: dict[Node, dict[str, Node]] = {node: {} for node in nodes}

    for node in children:
        if len(node) > 1:
            children[node[:-1]][node[-1]] = node

    return children


def _class_representatives(
    targets: Mapping[Node, Node], children: Mapping[Node, Mapping[str, Node]]
) -> dict[Node, Node]:
    representatives: dict[Node, Node] = {}
    representatives_by_signature: dict[ClassSignature, Node] = {}

    for node in sorted(targets, key=lambda item: (-len(item), item)):
        child_types = tuple((name, representatives[child]) for name, child in sorted(children[node].items()))
        signature = (targets[node], child_types)
        representatives[node] = representatives_by_signature.setdefault(signature, node)

    return representatives


def _node_name(node: Node) -> str:
    return sanitize_node(".".join(node))


def _shortest_paths(targets: Mapping[Node, Node]) -> list[Node]:
    shortest: dict[Node, Node] = {}

    for path, target in targets.items():
        if target not in shortest or (len(path), path) < (len(shortest[target]), shortest[target]):
            shortest[target] = path

    return sorted(shortest.values())


def generate_stubs(devdb: Mapping[str, str]) -> str:
    targets = _expanded_nodes(devdb)
    children = _children_by_node(targets)
    representatives = _class_representatives(targets, children)
    classes = sorted(set(representatives.values()))

    code = ""
    code += "# Generated by annet/annlib/netdev/devdb/generate_stubs.py\n"
    code += "# DO NOT MODIFY!\n"
    code += '"""\n'
    for node in _shortest_paths(targets):
        code += f"hw.{'.'.join(node)}\n"
    code += '"""\n'
    code += "from __future__ import annotations\n"
    code += "\n"
    code += "from annet.annlib.netdev.views.hardware import HardwareLeaf\n"
    code += "\n"
    code += "\n"

    for node in classes:
        code += f"class {_node_name(node)}(HardwareLeaf):\n"
        for name, child in sorted(children[node].items()):
            code += f"    {name}: {_node_name(representatives[child])}\n"
        if not children[node]:
            code += "    ...\n"
        code += "\n"

    code += "class FakeHardwareView(HardwareLeaf):\n"
    code += '    """\n'
    code += "    NOT TO BE USED AT RUNTIME\n"
    code += "    fake base class for HardwareView that has annotations for entire devdb\n"
    code += '    """\n'
    code += "\n"
    root_nodes = sorted(node for node in targets if len(node) == 1)
    for node in root_nodes:
        code += f"    {node[0]}: {_node_name(representatives[node])}\n"
    if not root_nodes:
        # devdb is empty?
        code += "    ...\n"

    return code


def _main() -> None:
    import json
    import sys

    if len(sys.argv) != 3:
        print(f"Usage: {sys.executable} {sys.argv[0]} <devdb.json> <generated.pyi>")
        sys.exit(2)

    file_devdb = sys.argv[1]
    file_code = sys.argv[2]

    with open(file_devdb, "r") as f:
        devdb = json.load(f)

    with open(file_code, "w") as f:
        f.write(generate_stubs(devdb))


if __name__ == "__main__":
    _main()
