generators:
  default:
    - annet_generators.example
    - annet_generators.mesh_example
    - annet_generators.rpl_example

storage:
  default:
    adapter: netbox

rulebook_module:
  default:
    - annet.rulebook.texts

context:
  default:
    generators: default
    storage: default
    rulebook_module: default

selected_context: default
